# Generated by Django 5.1.7 on 2025-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_last_game_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="selected_theme",
            field=models.CharField(default="default_theme", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="unlocked_themes",
            field=models.JSONField(default=list),
        ),
    ]
