# Generated by Django 5.1.7 on 2025-04-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_selected_theme_user_unlocked_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="champion_badge_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="is_in_loser_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_message_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
