# Generated by Django 5.1.7 on 2025-04-14 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_champion_badge_count_user_is_in_loser_room_and_more"),
        ("stocks", "0002_remove_stockroommembership_kicked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "stock")},
            },
        ),
    ]
