# Generated by Django 5.1.7 on 2025-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="지수명"),
                ),
                (
                    "symbol",
                    models.CharField(max_length=20, unique=True, verbose_name="심볼"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="가격"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="변동액"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="변동률(%)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="갱신일"),
                ),
            ],
            options={
                "verbose_name": "시장 지수",
                "verbose_name_plural": "시장 지수들",
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                (
                    "content_summary",
                    models.TextField(blank=True, null=True, verbose_name="내용 요약"),
                ),
                ("source", models.CharField(max_length=100, verbose_name="출처")),
                ("published_at", models.DateTimeField(verbose_name="발행일")),
                ("url", models.URLField(unique=True, verbose_name="기사 URL")),
                ("category", models.CharField(max_length=50, verbose_name="카테고리")),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="이미지 URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "related_symbols",
                    models.JSONField(
                        blank=True, default=list, verbose_name="관련 종목 코드"
                    ),
                ),
            ],
            options={
                "verbose_name": "뉴스 기사",
                "verbose_name_plural": "뉴스 기사들",
                "ordering": ["-published_at"],
            },
        ),
    ]
